### ISSUE TITLE
Got runtime error on simple class instance to instance comparison....

### ISSUE THREAD

**Issue by Glidias** [kevinresol/deep_equal#3]
Does your utility work? I tried to compare two instantiated fresh Item objects, an item like: https://github.com/Glidias/trosink/blob/master/haxe/src/troshx/sos/core/Item.hx  , but i get runtime error.

	
	package ;

	import deepequal.DeepEqual;
	import troshx.sos.core.Item;

	class Main 
	{
		
		static function main() 
		{
			var a =new Item();
			var b = new Item();
			DeepEqual.compare(a, b);
		}
		
	}

What i get in google chrome console:
`Uncaught js__$Boot_HaxeError {val: "Unhandled type: TFunction (<function>)", message: "Unhandled type: TFunction (<function>)", stack: "Error: Unhandled type: TFunction (<function>)↵ `

Also, why bother with deep comparing if a basic Serialize.toString() comparison would be fine? Or is Serialize.toString() comparison unreliable?? (ok, I do realise when dealing with dynamic hashes, the order of keys aren't consitent, so it might yield false negatives...)

	function compareItemsEq(a:Item, b:Item):Bool {
		var as:Serializer = new Serializer();
		var bs:Serializer = new Serializer();
		as.serialize(a);
		bs.serialize(b);
		return(as.toString() == bs.toString());
	}

**Comment by kevinresol** [comment]
Seems like your class instance holds a member variable which is a function?
function is not handled as hinted in the error message

**Comment by kevinresol** [comment]
> Also, why bother with deep comparing if a basic Serialize.toString() comparison would be fine?

I read twice and I am sure you wrote "if". And yes, the condition make sense. Then what is your "else" clause?

**Comment by Glidias** [comment]
The Item class doesn't seems to have a member variable holding a function though...

The Serialize.tostring()  method I suggested, however, will have its caveats for dynamic hashes and also might yield different serialized string order results  if you used a later version of your own codebase which might re-order/add new properties. So, it'll only be" tolerable" solution so long as the user is willing to conservatively accept false negatives when checking for equality.

**Comment by kevinresol** [comment]
> The Serialize.tostring() method I suggested, however, will have its caveats for dynamic hashes and also might yield different serialized string order results if you used a later version of your own codebase which might re-order/add new properties. So, it'll only be" tolerable" solution so long as the user is willing to conservatively accept false negatives when checking for equality.

So there you answered your own question already :)

> Also, why bother with deep comparing if a basic Serialize.toString() comparison would be fine?
